image: python:3.7

before_script:
  - apt-get update -qq && apt-get install -y -qq python3-pip
  - which python3
  - python3 --version
  - python3 -m pip install i3ipc pylint tox pytype

pylint:
  script: pylint i3wsgroups scripts/i3-workspace-groups

pytype_py36:
  image: python:3.6
  script: pytype i3wsgroups

pytype_py37:
  script: pytype i3wsgroups

test_py36:
  image: python:3.6
  script: tox -e py36

test_py37:
  script: tox -e py37
