name: i3_workspace_groups
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pylint
  - yapf
  - virtualenv
  - tox
  - tox-conda
  - pip
  - pip:
    - i3ipc
    - pytype
    - pyright
